name: Build App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # Fix 1: Verify and extract ZIP properly
    - name: Unzip source
      run: |
        if [ -f "yourfile.zip" ]; then
          unzip -o yourfile.zip -d app_source
        else
          echo "ZIP file missing!" && exit 1
        fi

    # Fix 2: Ensure execute permissions
    - name: Set permissions
      run: |
        cd app_source
        chmod +x gradlew  # For Android
        chmod +x ./scripts/*.sh  # For custom scripts

    # Fix 3: Use absolute paths for critical commands
    - name: Build
      run: |
        cd app_source
        /usr/bin/env bash ./gradlew assembleDebug  # Android
        # OR for Node: /usr/bin/npm install

    # Debug: List files to verify paths
    - name: Debug files
      run: |
        cd app_source
        ls -la
        pwd
